---
"$schema": "https://github.com/hyperledger-labs/fablo/releases/download/2.2.0/schema.json"
global:
  fabricVersion: "2.4.2"
  tls: false
  peerDevMode: false
  monitoring:
    loglevel: "debug"
  tools:
    explorer: false

orgs:
  - organization:
      name: "Orderer"
      domain: "root.com"
    orderers:
      - groupName: "group1"
        prefix: "orderer"
        type: "solo"
        instances: 1

  - organization:
      name: "Org1"
      domain: "org1.example.com"
    peer:
      instances: 1
      db: "LevelDb"
    tools:
      fabloRest: true
      explorer: true

  - organization:
      name: "Org2"
      domain: "org2.example.com"
    peer:
      instances: 1
      db: "LevelDb"
    tools:
      fabloRest: true

channels:
  - name: "mychannel"
    groupName: "group1"
    orgs:
      - name: "Org1"
        peers:
          - "peer0"
      - name: "Org2"
        peers:
          - "peer0"

chaincodes:
  - name: "bpmn-contract"
    version: "1.0"
    lang: "node"
    channel: "mychannel"
    directory: "./SmartContractHyperledger"
    initRequired: true
    endorsement: "OR('Org1MSP.member','Org2MSP.member')"

# REST API
rest:
  port: 3000
  enabled: true 