---
"$schema": "https://github.com/hyperledger-labs/fablo/releases/download/2.2.0/schema.json"
global:
  fabricVersion: "2.4.2"
  tls: false
  peerDevMode: false

orgs:
  - organization:
      name: "Orderer"
      domain: "root.com"
    orderers:
      - groupName: "group1"
        prefix: "orderer"
        type: "solo"
        instances: 1

  - organization:
      name: "Org1"
      domain: "org1.example.com"
    peer:
      instances: 1
    tools:
      fabloRest: true

channels:
  - name: "mychannel"
    groupName: "group1"
    orgs:
      - name: "Org1"
        peers:
          - "peer0"

chaincodes:
  - name: "bpmn-contract"
    version: "1.0"
    lang: "node"
    channel: "mychannel"
    directory: "./SmartContractHyperledger"
    initRequired: true 